package main

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/thomasf/neotrellis-seq/pkg/midimap"
)

// generateMidiMapH generates C++ source code for src/midimap.h.
func generateMidiMapH() string {
	var sb strings.Builder
	sb.WriteString(`// Code generated by cmd/neotrellis-seq-generator (midimap); DO NOT EDIT.
// Any manual changes will be overwritten. Edit pkg/midimap instead.

#ifndef MIDIMAP_H
#define MIDIMAP_H

#include <cstdint>

#ifndef VOICES
#define VOICES 6
#endif

`)
	sb.WriteString(fmt.Sprintf("// %s.\n", midimap.Default.Description))
	sb.WriteString(fmt.Sprintf("// Defined in pkg/midimap (Default setting: %s).\n", midimap.Default.Name))
	sb.WriteString("// Default voice mapping:\n")
	for _, v := range midimap.Voices {
		sb.WriteString(fmt.Sprintf("// - V%d: %s (%d / %s)\n", v.VoiceIndex, v.ConfigPrimaryName, v.PrimaryNote, midimap.MidiNoteName(v.PrimaryNote)))
	}
	sb.WriteString("struct VoiceNoteMap {\n")
	sb.WriteString("  uint8_t base;\n")
	sb.WriteString("};\n\n")

	sb.WriteString("constexpr VoiceNoteMap ACTIVE_VOICE_MAP[VOICES] = {\n")
	for _, v := range midimap.Voices {
		sb.WriteString(fmt.Sprintf("    {%d}, // Voice %d: %s (%d)\n",
			v.PrimaryNote, v.VoiceIndex, v.ConfigPrimaryName, v.PrimaryNote))
	}
	sb.WriteString("};\n\n")
	sb.WriteString("#endif // MIDIMAP_H\n")

	return sb.String()
}

// generateMidiMaps writes src/midimap.h.
func generateMidiMaps(rootDir string) error {
	midimapHPath := filepath.Join(rootDir, "src", "midimap.h")
	fmt.Printf("Updating %s...\n", midimapHPath)
	return writeGeneratedCHeader(midimapHPath, []byte(generateMidiMapH()))
}
