// Code generated by cmd/neotrellis-seq-generator (palette); DO NOT EDIT.
// Any manual changes will be overwritten.

#ifndef COLORS_H
#define COLORS_H

uint32_t static const COLOR_GREEN = 0x20D020;
uint32_t static const COLOR_OFF = 0x000000;
uint32_t static const COLOR_PACT = 0x8080B0;
uint32_t static const COLOR_PMOD = 0x808B80;
uint32_t static const COLOR_PPOS = 0xD0D0D0;
uint32_t static const COLOR_RED = 0xD02020;
uint32_t static const COLOR_TOOL = 0x902020;
uint32_t static const COLOR_VOC0 = 0x2050E0;
uint32_t static const COLOR_VOC0_ACCENT = 0xC5C6FF;
uint32_t static const COLOR_VOC0_SET = 0x5E72FF;
uint32_t static const COLOR_VOC0_UNSET = 0x000077;
uint32_t static const COLOR_VOC1 = 0xAD8920;
uint32_t static const COLOR_VOC1_ACCENT = 0xFFFF9C;
uint32_t static const COLOR_VOC1_SET = 0xD6AE47;
uint32_t static const COLOR_VOC1_UNSET = 0x472F00;
uint32_t static const COLOR_VOC2 = 0x20BCAF;
uint32_t static const COLOR_VOC2_ACCENT = 0xBCFFFF;
uint32_t static const COLOR_VOC2_SET = 0x59E4D6;
uint32_t static const COLOR_VOC2_UNSET = 0x00584F;
uint32_t static const COLOR_VOC3 = 0x489120;
uint32_t static const COLOR_VOC3_ACCENT = 0xC9FF9B;
uint32_t static const COLOR_VOC3_SET = 0x6FB746;
uint32_t static const COLOR_VOC3_UNSET = 0x003200;
uint32_t static const COLOR_VOC4 = 0xB030B0;
uint32_t static const COLOR_VOC4_ACCENT = 0xFFB5FF;
uint32_t static const COLOR_VOC4_SET = 0xD95AD7;
uint32_t static const COLOR_VOC4_UNSET = 0x46004E;
uint32_t static const COLOR_VOC5 = 0x808000;
uint32_t static const COLOR_VOC5_ACCENT = 0xFFFD88;
uint32_t static const COLOR_VOC5_SET = 0xA7A432;
uint32_t static const COLOR_VOC5_UNSET = 0x2A2600;

#endif
