// Code generated by cmd/neotrellis-seq-generator (midimap); DO NOT EDIT.
// Any manual changes will be overwritten. Edit pkg/midimap instead.

#ifndef MIDIMAP_H
#define MIDIMAP_H

#include <cstdint>

#ifndef VOICES
#define VOICES 6
#endif

// Ableton Drum Rack / General MIDI voice mapping (C1–D#2, notes 36–51).
// Defined in pkg/midimap (Default setting: gm_ableton).
// Default voice mapping:
// - V0: Kick (36 / C1)
// - V1: Snare (38 / D1)
// - V2: Closed Hi-Hat (42 / F#1)
// - V3: Low Floor Tom (41 / F1)
// - V4: Low Tom (45 / A1)
// - V5: Crash Cymbal (49 / C#2)
struct VoiceNoteMap {
  uint8_t base;
};

constexpr VoiceNoteMap ACTIVE_VOICE_MAP[VOICES] = {
    {36}, // Voice 0: Kick (36)
    {38}, // Voice 1: Snare (38)
    {42}, // Voice 2: Closed Hi-Hat (42)
    {41}, // Voice 3: Low Floor Tom (41)
    {45}, // Voice 4: Low Tom (45)
    {49}, // Voice 5: Crash Cymbal (49)
};

#endif // MIDIMAP_H
