// Code generated by contrib/patterns.go from patterns.txt; DO NOT EDIT.
// Any manual changes will be overwritten. Edit patterns.txt instead.

#ifndef PATTERN_PRESETS_H
#define PATTERN_PRESETS_H

#include "Sequencer.h"
#include "config.h"
#include <cstdint>

namespace PatternPresets {

// Velocity shorthand constants for pattern definitions
static constexpr uint8_t A = ACCENT_VELOCITY;  // 127: Accented step
static constexpr uint8_t N = DEFAULT_VELOCITY; // 99:  Standard step
static constexpr uint8_t g = GHOST_VELOCITY;   // 50:  Muted / ghost step
static constexpr uint8_t _ = 0;                // 0:   Rest / silence

struct Preset {
  const char *name;
  uint8_t velocities[16];
};

// -----------------------------------------------------------------------------
// Voice-Specific Pattern Presets (16 patterns each, mapped to STEP 1..16)
// Triggered via: FN + ACCENT + STEP n (for the selected voice)
//
// Voice 0: Kick / Bass Drum
// Voice 1: Snare / Clap
// Voice 2: Hi-Hat
// Voice 3, 4, 5: Percussion 1 (Low), Percussion 2 (Mid), Percussion 3 (High)
// -----------------------------------------------------------------------------

// Voice 0: Kick / Bass Drum Presets
static constexpr Preset KICK_PRESETS[16] = {
    // Row 0 (Pads 1-4)
    {"Four on Floor", {A, _, _, _, A, _, _, _, A, _, _, _, A, _, _, _}},
    {"Four on Floor Pickup", {A, _, _, _, N, _, _, _, A, _, _, _, N, _, _, g}},
    {"Pumping 4/4 Drive", {A, _, _, g, N, _, _, _, A, _, _, g, N, _, _, _}},
    {"Berlin Rumble 4/4", {A, _, _, _, A, _, _, _, A, _, _, _, A, _, N, _}},

    // Row 1 (Pads 5-8)
    {"Dembow Reggaeton", {A, _, _, _, A, _, _, _, A, _, N, _, A, _, _, _}},
    {"Tresillo 3-3-2", {A, _, _, N, _, _, A, _, A, _, _, N, _, _, A, _}},
    {"Afro-House Minimal", {A, _, _, _, _, _, A, _, A, _, _, _, N, _, _, _}},
    {"Samba Surdo Bounce", {A, _, _, N, _, _, A, _, _, _, A, _, _, N, _, _}},

    // Row 2 (Pads 9-12)
    {"UK Garage 2-Step", {A, _, _, _, _, _, _, A, _, _, _, _, _, _, _, _}},
    {"Electro 808 Sync", {A, _, _, N, _, _, _, _, A, _, _, N, _, _, N, _}},
    {"Breakbeat Funk", {A, _, _, _, _, _, A, _, _, _, A, _, _, _, _, _}},
    {"Baile Favela Drop", {A, _, _, N, _, _, N, _, A, _, _, N, _, _, _, _}},

    // Row 3 (Pads 13-16)
    {"Offbeat Skip Kick", {A, _, _, _, N, _, _, _, _, _, A, _, N, _, _, _}},
    {"Dub Techno Deep", {A, _, _, _, _, _, _, _, A, _, _, _, _, _, _, _}},
    {"Microhouse Minimal", {A, _, _, _, _, _, _, _, N, _, _, _, _, _, _, g}},
    {"Dotted 8th Phasing", {A, _, _, N, _, _, A, _, _, N, _, _, A, _, _, _}},
};

// Voice 1: Snare / Clap Presets
static constexpr Preset SNARE_PRESETS[16] = {
    // Row 0 (Pads 1-4)
    {"Classic Backbeat", {_, _, _, _, A, _, _, _, _, _, _, _, A, _, _, _}},
    {"Backbeat & Flam", {_, _, _, _, A, _, _, _, _, _, _, _, A, _, _, g}},
    {"Double Clap Pump", {_, _, _, _, A, _, _, _, _, _, _, _, A, N, _, _}},
    {"House Backbeat Roll", {_, _, _, _, A, _, _, _, _, _, g, g, A, _, _, _}},

    // Row 1 (Pads 5-8)
    {"Dembow Syncopation", {_, _, _, A, _, _, A, _, _, _, _, A, _, _, A, _}},
    {"Tresillo Snare", {_, _, _, A, _, _, A, _, _, _, _, A, _, _, _, _}},
    {"Afro Woodblock Drop", {_, _, _, _, _, _, _, _, A, _, _, _, _, _, _, _}},
    {"Samba Caixa Roll", {_, _, _, g, A, _, _, g, _, _, _, g, A, _, g, _}},

    // Row 2 (Pads 9-12)
    {"UKG 2-Step Snare", {_, _, _, _, A, _, _, _, _, _, _, _, A, _, N, _}},
    {"Electro 808 Snare", {_, _, _, _, A, _, _, g, _, _, _, _, A, _, _, _}},
    {"Breakbeat Ghost", {_, _, _, _, A, _, _, g, _, g, _, _, A, _, _, g}},
    {"Baile Funk Snare", {_, _, _, _, A, _, _, A, _, _, _, _, A, _, _, _}},

    // Row 3 (Pads 13-16)
    {"Roll Down",
     {127, 122, 117, 112, 106, 101, 96, 91, 86, 81, 76, 71, 65, 60, 55, 50}},
    {"Roll Up",
     {50, 55, 60, 65, 71, 76, 81, 86, 91, 96, 101, 106, 112, 117, 122, 127}},
    {"Roll Up-Down",
     {50, 61, 72, 83, 94, 105, 116, 127, 127, 116, 105, 94, 83, 72, 61, 50}},
    {"Roll Down-Up",
     {127, 116, 105, 94, 83, 72, 61, 50, 50, 61, 72, 83, 94, 105, 116, 127}},
};

// Voice 2: Hi-Hat Presets
static constexpr Preset HIHAT_PRESETS[16] = {
    // Row 0 (Pads 1-4)
    {"Classic Offbeat Open", {_, _, A, _, _, _, A, _, _, _, A, _, _, _, A, _}},
    {"Offbeat & Pickup", {_, _, A, _, _, _, A, _, _, _, A, _, _, g, A, _}},
    {"Straight 8th Notes", {N, _, A, _, N, _, A, _, N, _, A, _, N, _, A, _}},
    {"Minimal Dub Ticks", {_, _, A, _, _, _, _, _, _, _, A, _, _, _, _, _}},

    // Row 1 (Pads 5-8)
    {"UKG Swung Skip", {N, _, A, _, _, g, A, _, N, _, A, _, _, g, A, _}},
    {"Breakbeat Swung 8ths", {N, _, A, g, N, _, A, _, N, _, A, g, N, _, A, _}},
    {"Cumbia Guiro Scrape", {_, N, _, A, _, N, _, A, _, N, _, A, _, N, _, A}},
    {"Afro Feathered Hat", {_, _, A, g, _, _, A, _, _, _, A, g, _, _, A, _}},

    // Row 2 (Pads 9-12)
    {"Dotted 8th Phasing", {A, _, _, N, _, _, A, _, _, N, _, _, A, _, _, _}},
    {"Microhouse Delicate", {_, _, A, _, _, _, _, g, _, _, A, _, _, _, _, _}},
    {"Downbeat Ticks", {A, _, _, _, N, _, _, _, A, _, _, _, N, _, _, _}},
    {"Half-Time Triplet", {A, _, _, N, _, _, N, _, A, _, _, N, _, _, N, _}},

    // Row 3 (Pads 13-16)
    {"Chicago 909 Groove", {N, g, A, g, N, g, A, g, N, g, A, g, N, g, A, g}},
    {"Detroit Electro 16ths", {N, g, N, A, N, g, N, A, N, g, N, A, N, g, N, A}},
    {"Berlin Peak 16ths", {A, g, N, g, A, g, N, g, A, g, N, g, A, g, N, g}},
    {"Batucada Samba Roll", {A, g, A, g, A, g, A, g, A, g, A, g, A, g, A, g}},
};

// Voice 3: Percussion 1 Presets (Low/Mid)
static constexpr Preset PERC1_PRESETS[16] = {
    // Row 0 (Pads 1-4)
    {"Low Conga Tumbao", {_, _, _, _, _, _, A, _, _, _, _, _, _, _, N, _}},
    {"Low Conga Bounce", {_, _, _, _, _, _, A, _, _, _, _, _, _, N, _, _}},
    {"Afro Low Tumbadora", {A, _, _, N, _, _, A, _, _, _, N, _, _, _, _, _}},
    {"Guaguanco Low Hit", {_, _, A, _, _, _, _, N, _, _, A, _, _, _, _, _}},

    // Row 1 (Pads 5-8)
    {"Low Tom Downbeat", {A, _, _, _, _, _, _, _, A, _, _, _, _, _, _, _}},
    {"Rolling Tribal Low", {_, _, N, _, _, _, N, _, _, _, N, _, _, _, N, _}},
    {"808 Low Tom Sync", {_, _, _, _, _, _, A, _, _, _, _, _, _, _, A, _}},
    {"Dub Reso-Tom", {_, _, _, _, A, _, _, _, _, _, _, _, _, _, _, _}},

    // Row 2 (Pads 9-12)
    {"Afro Woodblock Beat 3", {_, _, _, _, _, _, _, _, A, _, _, _, _, _, _, _}},
    {"Woodblock Clack 3:2", {A, _, _, N, _, _, _, A, _, _, N, _, A, _, _, _}},
    {"Sub Bass Drop 1", {A, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _}},
    {"Sub Bass 2-Step", {A, _, _, _, _, _, _, A, _, _, _, _, _, _, _, _}},

    // Row 3 (Pads 13-16)
    {"Cumbia Low Tumbao", {_, _, _, _, _, _, N, _, _, _, _, _, _, _, N, _}},
    {"Breakbeat Low Tom", {_, _, _, _, _, _, _, _, N, _, _, _, _, _, _, _}},
    {"Microhouse Low Wood", {_, _, _, _, _, N, _, _, _, _, _, _, _, N, _, _}},
    {"Dotted 8th Low Pulse", {A, _, _, N, _, _, A, _, _, N, _, _, A, _, _, _}},
};

// Voice 4: Percussion 2 Presets (Mid/High)
static constexpr Preset PERC2_PRESETS[16] = {
    // Row 0 (Pads 1-4)
    {"High Conga Slap", {_, _, _, _, A, _, _, _, _, _, _, _, _, _, _, _}},
    {"Afro Conga Slaps", {_, _, _, _, _, _, _, A, _, _, _, _, _, A, _, _}},
    {"Rumba Clave 3:2", {A, _, _, N, _, _, _, A, _, _, N, _, A, _, _, _}},
    {"Son Clave 3:2", {A, _, _, N, _, _, A, _, _, _, N, _, A, _, _, _}},

    // Row 1 (Pads 5-8)
    {"Syncopated Cowbell", {_, _, A, _, _, _, A, _, _, _, A, _, _, _, _, _}},
    {"Campana Cumbia Bell", {A, _, _, _, _, _, A, _, _, _, A, _, _, _, A, _}},
    {"808 Cowbell Sync", {A, _, _, _, _, _, _, _, A, _, _, _, _, _, _, _}},
    {"Agogo Bell Mid/High", {A, _, N, _, A, _, _, A, _, N, _, _, N, _, A, _}},

    // Row 2 (Pads 9-12)
    {"House Rimshot Sync", {_, _, _, _, _, _, _, _, _, _, N, _, _, _, _, _}},
    {"UKG Rim Counter-Skip", {_, _, _, N, _, _, _, _, _, _, _, _, _, _, _, N}},
    {"Dembow Clack Accent", {_, _, _, _, _, _, _, _, _, N, _, _, _, _, _, _}},
    {"Microhouse Org Pop", {_, _, _, _, _, _, A, _, _, _, _, _, _, _, _, _}},

    // Row 3 (Pads 13-16)
    {"Dub Techno Stabs", {_, _, A, _, _, _, _, _, _, N, _, _, _, _, _, _}},
    {"Mid Tom Response", {_, _, _, _, A, _, _, _, _, _, _, _, A, _, _, _}},
    {"Timbale End Roll", {_, _, _, _, _, _, _, _, _, _, _, _, _, A, N, A}},
    {"Industrial Metal Anvil",
     {_, _, _, _, N, _, _, _, _, _, _, _, N, _, _, _}},
};

// Voice 5: Percussion 3 Presets (High/Texture)
static constexpr Preset PERC3_PRESETS[16] = {
    // Row 0 (Pads 1-4)
    {"Gentle 8th Shaker", {_, g, _, N, _, g, _, N, _, g, _, N, _, g, _, N}},
    {"Minimal Shaker Touch", {_, _, _, N, _, _, _, N, _, _, _, N, _, _, _, N}},
    {"Afro Seed Shaker", {_, g, _, N, _, g, _, N, _, g, _, N, _, g, _, N}},
    {"Continuous 16th Shaker",
     {g, N, g, N, g, N, g, N, g, N, g, N, g, N, g, N}},

    // Row 1 (Pads 5-8)
    {"Backbeat Tambourine", {_, _, _, _, A, _, _, _, _, _, _, _, A, _, _, _}},
    {"Offbeat Tambourine", {_, _, N, _, _, _, N, _, _, _, N, _, _, _, N, _}},
    {"Samba Repinique", {_, g, _, N, _, g, _, N, _, g, _, N, _, g, _, N}},
    {"Tamborim 16ths", {A, g, N, g, A, g, N, g, A, g, N, g, A, g, N, g}},

    // Row 2 (Pads 9-12)
    {"Offbeat Ride Cymbal", {_, _, N, _, _, _, N, _, _, _, N, _, _, _, N, _}},
    {"Downbeat Ride Ping", {A, _, _, _, _, _, _, _, A, _, _, _, _, _, _, _}},
    {"Single Ride Accent", {_, _, _, _, _, _, A, _, _, _, _, _, _, _, _, _}},
    {"Ride Cymbal 8ths", {N, _, N, _, N, _, N, _, N, _, N, _, N, _, N, _}},

    // Row 3 (Pads 13-16)
    {"Vinyl Dust & Clicks", {g, _, _, _, _, _, _, _, g, _, _, _, _, _, _, _}},
    {"Tape Crackle Echo", {_, _, _, _, _, _, _, _, _, _, _, _, g, _, _, _}},
    {"High Tom Accent Roll", {A, _, _, _, _, _, A, _, _, _, _, _, A, _, _, _}},
    {"Bongo Slap Flam", {_, _, _, _, _, _, _, _, _, _, _, _, _, _, N, A}},
};

inline void apply_preset(uint32_t voice, Pattern *p, uint32_t preset_index) {
  if (!p || voice >= VOICES || preset_index >= 16) {
    return;
  }
  const Preset *preset_list = nullptr;
  switch (voice) {
  case 0:
    preset_list = KICK_PRESETS;
    break;
  case 1:
    preset_list = SNARE_PRESETS;
    break;
  case 2:
    preset_list = HIHAT_PRESETS;
    break;
  case 3:
    preset_list = PERC1_PRESETS;
    break;
  case 4:
    preset_list = PERC2_PRESETS;
    break;
  case 5:
    preset_list = PERC3_PRESETS;
    break;
  default:
    return;
  }
  const Preset &preset = preset_list[preset_index];
  p->length = 16;
  for (uint32_t i = 0; i < 16; ++i) {
    p->steps[i] = Step(preset.velocities[i]);
  }
}

// -----------------------------------------------------------------------------
// 16 Full 6-Voice Coordinated Kits
// Triggered via: FN + ALL + ACCENT + STEP n (for the entire kit)
//
// Voices:
//   Voice 0: Kick / Bass Drum
//   Voice 1: Snare / Clap
//   Voice 2: Hi-Hat
//   Voice 3: Percussion 1 (Low/Mid)
//   Voice 4: Percussion 2 (Mid/High)
//   Voice 5: Percussion 3 (High/Texture)
// -----------------------------------------------------------------------------

struct KitPreset {
  const char *name;
  const char *genre;
  uint8_t voices[VOICES][16];
};

static constexpr KitPreset KITS[16] = {
    // -------------------------------------------------------------------------
    // Row 0 (Pads 1-4)
    // -------------------------------------------------------------------------
    // Kit 0 (Step 1): Classic Chicago House
    {"Classic Chicago House",
     "House",
     {
         {_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _},
         {_, _, _, _, A, _, _, _, _, _, _, _, A, _, _, _},
         {_, _, A, _, _, _, A, _, _, _, A, _, _, _, A, _},
         {_, _, _, _, _, _, A, _, _, _, _, _, _, N, _, _},
         {_, _, _, _, _, _, _, _, _, _, N, _, _, _, _, _},
         {_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _},
     }},

    // Kit 1 (Step 2): French Touch Disco
    {"French Touch Disco",
     "Nu-Disco",
     {
         {A, _, _, _, A, _, _, _, A, _, _, _, A, _, _, _},
         {_, _, _, _, A, _, _, _, _, _, _, _, A, _, _, _},
         {N, _, A, _, N, _, A, _, N, _, A, _, N, _, A, _},
         {_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, N},
         {_, _, A, _, _, _, _, _, _, _, A, _, _, _, _, _},
         {_, _, _, _, N, _, _, _, _, _, _, _, N, _, _, _},
     }},

    // Kit 2 (Step 3): Deep House Sunset
    {"Deep House Sunset",
     "Deep House",
     {
         {A, _, _, _, N, _, _, _, A, _, _, _, N, _, _, g},
         {_, _, _, _, A, _, _, _, _, _, _, _, A, _, _, _},
         {_, _, A, _, _, _, A, _, _, _, A, _, _, _, A, _},
         {_, _, _, _, _, _, A, _, _, _, _, _, _, _, N, _},
         {_, _, _, _, _, _, _, _, _, _, A, _, _, _, _, _},
         {_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _},
     }},

    // Kit 3 (Step 4): Garage House Shuffle
    {"Garage House Shuffle",
     "Garage House",
     {
         {A, _, _, _, N, _, _, _, A, _, _, _, N, _, _, _},
         {_, _, _, _, A, _, _, _, _, _, _, _, A, _, N, _},
         {N, _, A, _, _, g, A, _, N, _, A, _, _, g, A, _},
         {_, _, _, _, _, _, N, _, _, _, _, _, _, _, _, _},
         {_, _, _, N, _, _, _, _, _, _, _, _, _, _, _, _},
         {_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _},
     }},

    // -------------------------------------------------------------------------
    // Row 1 (Pads 5-8)
    // -------------------------------------------------------------------------
    // Kit 4 (Step 5): Afro-House Keinemusik
    {"Afro-House Keinemusik",
     "Afro-House",
     {
         {A, _, _, _, N, _, _, _, A, _, _, _, N, _, _, _},
         {_, _, _, _, _, _, _, _, A, _, _, _, _, _, _, _},
         {_, _, A, _, _, _, A, _, _, _, A, _, _, _, A, _},
         {A, _, _, N, _, _, A, _, _, _, N, _, _, _, _, _},
         {_, _, _, _, _, _, _, A, _, _, _, _, _, A, _, _},
         {_, g, _, N, _, g, _, N, _, g, _, N, _, g, _, N},
     }},

    // Kit 5 (Step 6): Electro-Cumbia
    {"Electro-Cumbia",
     "Cumbia",
     {
         {A, _, _, _, N, _, _, _, A, _, _, _, N, _, _, _},
         {_, _, _, _, A, _, _, _, _, _, _, _, A, _, _, _},
         {_, N, _, A, _, N, _, A, _, N, _, A, _, N, _, A},
         {_, _, _, _, _, _, N, _, _, _, _, _, _, _, N, _},
         {A, _, _, _, _, _, A, _, _, _, A, _, _, _, _, _},
         {_, _, _, _, _, _, _, _, _, _, _, _, _, _, A, _},
     }},

    // Kit 6 (Step 7): Dembow Latin Club
    {"Dembow Latin Club",
     "Dembow",
     {
         {A, _, _, _, A, _, _, _, A, _, _, _, A, _, _, _},
         {_, _, _, A, _, _, A, _, _, _, _, A, _, _, A, _},
         {_, _, A, _, _, _, A, _, _, _, A, _, _, _, A, _},
         {A, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _},
         {_, _, _, _, _, _, _, _, _, N, _, _, _, _, _, _},
         {_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _},
     }},

    // Kit 7 (Step 8): Batucada Carnival
    {"Batucada Carnival",
     "Samba",
     {
         {A, _, _, N, _, _, A, _, _, _, A, _, _, N, _, _},
         {_, _, _, g, A, _, _, g, _, _, _, g, A, _, g, _},
         {A, g, A, g, A, g, A, g, A, g, A, g, A, g, A, g},
         {_, _, _, _, A, _, _, _, _, _, _, _, A, _, _, _},
         {A, _, N, _, A, _, _, A, _, N, _, _, N, _, A, _},
         {_, g, _, N, _, g, _, N, _, g, _, N, _, g, _, N},
     }},

    // -------------------------------------------------------------------------
    // Row 2 (Pads 9-12)
    // -------------------------------------------------------------------------
    // Kit 8 (Step 9): UK Garage 2-Step
    {"UK Garage 2-Step",
     "UKG",
     {
         {A, _, _, _, _, _, _, A, _, _, _, _, _, _, _, _},
         {_, _, _, _, A, _, _, _, _, _, _, _, A, _, _, _},
         {N, _, A, _, _, g, A, _, N, _, A, _, _, g, A, _},
         {_, _, _, _, _, _, _, _, _, _, N, _, _, _, _, _},
         {_, _, _, N, _, _, _, _, _, _, _, _, _, _, N, _},
         {_, _, _, _, _, _, A, _, _, _, _, _, _, _, _, _},
     }},

    // Kit 9 (Step 10): Detroit Electro 808
    {"Detroit Electro 808",
     "Electro",
     {
         {A, _, _, N, _, g, _, _, A, _, _, N, _, _, N, _},
         {_, _, _, _, A, _, _, _, _, _, _, _, A, _, _, _},
         {N, g, N, A, N, g, N, A, N, g, N, A, N, g, N, A},
         {_, _, _, _, _, _, A, _, _, _, _, _, _, _, _, _},
         {A, _, _, _, _, _, _, _, A, _, _, _, _, _, _, _},
         {_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _},
     }},

    // Kit 10 (Step 11): Breakbeat Shuffle
    {"Breakbeat Shuffle",
     "Breaks",
     {
         {A, _, _, _, _, _, A, _, _, _, A, _, _, _, _, _},
         {_, _, _, g, A, _, _, g, _, g, _, _, A, _, _, g},
         {N, _, A, g, N, _, A, _, N, _, A, g, N, _, A, _},
         {_, _, _, _, _, _, _, _, N, _, _, _, _, _, _, _},
         {_, _, _, N, _, _, _, _, _, _, _, _, _, _, _, _},
         {_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _},
     }},

    // Kit 11 (Step 12): Baile Funk Bounce
    {"Baile Funk Bounce",
     "Bass",
     {
         {A, _, _, N, _, _, N, _, A, _, _, N, _, _, _, _},
         {_, _, _, _, A, _, _, _, _, _, _, _, A, _, _, _},
         {_, _, A, _, _, _, A, _, _, _, A, _, _, _, A, _},
         {A, _, _, _, _, _, _, _, A, _, _, _, _, _, _, _},
         {_, _, _, A, _, _, A, _, _, _, _, A, _, _, A, _},
         {_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _},
     }},

    // -------------------------------------------------------------------------
    // Row 3 (Pads 13-16)
    // -------------------------------------------------------------------------
    // Kit 12 (Step 13): Berlin Peak Techno
    {"Berlin Peak Techno",
     "Techno",
     {
         {A, _, _, _, A, _, _, _, A, _, _, _, A, _, _, _},
         {_, _, _, _, A, _, _, _, _, _, _, _, A, _, _, _},
         {N, g, A, g, N, g, A, g, N, g, A, g, N, g, A, g},
         {_, _, _, A, _, _, _, _, _, A, _, _, _, _, A, _},
         {_, _, _, _, N, _, _, _, _, _, _, _, N, _, _, _},
         {_, _, N, _, _, _, N, _, _, _, N, _, _, _, N, _},
     }},

    // Kit 13 (Step 14): Dub Techno Echo
    {"Dub Techno Echo",
     "Dub Techno",
     {
         {A, _, _, _, N, _, _, _, A, _, _, _, N, _, _, _},
         {_, _, _, _, _, _, _, _, A, _, _, _, _, _, _, _},
         {_, _, A, _, _, _, _, _, _, _, A, _, _, _, _, _},
         {_, _, _, _, A, _, _, _, _, _, _, _, _, _, _, _},
         {_, _, A, _, _, _, _, _, _, N, _, _, _, _, _, _},
         {_, _, _, _, _, _, _, _, _, _, _, _, g, _, _, _},
     }},

    // Kit 14 (Step 15): Romanian Microhouse
    {"Romanian Microhouse",
     "Microhouse",
     {
         {A, _, _, _, N, _, _, _, A, _, _, _, N, _, _, _},
         {_, _, _, _, A, _, _, _, _, _, _, _, A, _, _, _},
         {_, _, A, _, _, _, _, g, _, _, A, _, _, _, _, _},
         {_, _, _, _, _, N, _, _, _, _, _, _, _, N, _, _},
         {_, _, _, _, _, _, A, _, _, _, _, _, _, _, _, _},
         {g, _, _, _, _, _, _, _, g, _, _, _, _, _, _, _},
     }},

    // Kit 15 (Step 16): Driving Hardgroove
    {"Driving Hardgroove",
     "Hardgroove",
     {
         {A, _, _, _, A, _, _, _, A, _, _, _, A, _, _, _},
         {_, _, _, _, A, _, _, _, _, _, _, _, A, _, _, _},
         {A, g, A, g, A, g, A, g, A, g, A, g, A, g, A, g},
         {_, _, N, _, _, _, N, _, _, _, N, _, _, _, N, _},
         {_, _, _, _, A, _, _, _, _, _, _, _, A, _, _, _},
         {A, _, _, _, _, _, A, _, _, _, _, _, A, _, _, _},
     }},

};

inline void apply_kit_voice(uint32_t voice, uint32_t kit_index, Pattern *p) {
  if (!p || voice >= VOICES || kit_index >= 16) {
    return;
  }
  const auto &pattern_data = KITS[kit_index].voices[voice];
  p->length = 16;
  for (uint32_t i = 0; i < 16; ++i) {
    p->steps[i] = Step(pattern_data[i]);
  }
}

} // namespace PatternPresets

namespace DancePatterns = PatternPresets;

#endif // PATTERN_PRESETS_H
