// Code generated by cmd/neotrellis-seq-generator (patterns) from patterns.txt; DO NOT EDIT.
// Any manual changes will be overwritten. Edit patterns.txt instead.

#ifndef PATTERN_PRESETS_H
#define PATTERN_PRESETS_H

#include "Sequencer.h"
#include "config.h"
#include <cstdint>

namespace PatternPresets {

// Velocity shorthand constants for pattern definitions
static constexpr uint8_t A = ACCENT_VELOCITY;  // 127: Accented step
static constexpr uint8_t N = DEFAULT_VELOCITY; // 99:  Standard step
static constexpr uint8_t g = GHOST_VELOCITY;   // 50:  Muted / ghost step
static constexpr uint8_t _ = 0;                // 0:   Rest / silence

struct Preset {
  const char *name;
  uint8_t length;
  uint8_t velocities[PATTERN_STEPS];
};

// -----------------------------------------------------------------------------
// Voice-Specific Pattern Presets (16 patterns each, mapped to STEP 1..16)
// Triggered via: FN1 + ACCENT + STEP n (for the selected voice)
//
// Voice 0: Kick / Bass Drum
// Voice 1: Snare / Clap
// Voice 2: Hi-Hat
// Voice 3, 4, 5: Percussion 1 (Low), Percussion 2 (Mid), Percussion 3 (High)
// -----------------------------------------------------------------------------

// Voice 0: Kick / Bass Drum Presets
static constexpr Preset KICK_PRESETS[16] = {
    // Row 0 (Pads 1-4)
    {"Four on Floor", 16, {A, _, _, _, A, _, _, _, A, _, _, _, A, _, _, _}},
    {"Four on Floor Pickup", 32, {A, _, _, _, N, _, _, _, A, _, _, _, N, _, _, g,
                                  A, _, _, _, N, _, _, _, A, _, _, _, N, _, g, A}},
    {"Pumping 4/4 Drive", 16, {A, _, _, g, N, _, _, _, A, _, _, g, N, _, _, _}},
    {"Berlin Rumble 4/4", 32, {A, _, _, _, A, _, _, _, A, _, _, _, A, _, N, _,
                               A, _, _, _, A, _, _, _, A, _, _, _, A, N, N, _}},

    // Row 1 (Pads 5-8)
    {"Dembow Reggaeton", 16, {A, _, _, _, A, _, _, _, A, _, N, _, A, _, _, _}},
    {"Tresillo 3-3-2", 32, {A, _, _, N, _, _, A, _, A, _, _, N, _, _, A, _,
                            A, _, _, N, _, _, A, _, _, _, A, _, _, _, A, _}},
    {"Afro-House Minimal", 16, {A, _, _, _, _, _, A, _, A, _, _, _, N, _, _, _}},
    {"Samba Surdo Bounce", 32, {A, _, _, N, _, _, A, _, _, _, A, _, _, N, _, _,
                                A, _, _, N, _, _, A, _, _, _, A, _, _, A, N, _}},

    // Row 2 (Pads 9-12)
    {"UK Garage 2-Step", 16, {A, _, _, _, _, _, _, A, _, _, _, _, _, _, _, _}},
    {"Electro 808 Sync", 32, {A, _, _, N, _, _, _, _, A, _, _, N, _, _, N, _,
                              A, _, _, N, _, _, _, _, A, _, _, N, N, _, N, _}},
    {"Breakbeat Funk", 16, {A, _, _, _, _, _, A, _, _, _, A, _, _, _, _, _}},
    {"Baile Favela Drop", 32, {A, _, _, N, _, _, N, _, A, _, _, N, _, _, _, _,
                               A, _, _, N, _, _, N, _, A, _, _, N, N, _, A, _}},

    // Row 3 (Pads 13-16)
    {"Offbeat Skip Kick", 16, {A, _, _, _, N, _, _, _, _, _, A, _, N, _, _, _}},
    {"Dub Techno Deep", 64, {A, _, _, _, _, _, _, _, A, _, _, _, _, _, _, _, A, _, _, _, _, _,
                             _, _, _, _, _, _, _, _, _, _, A, _, _, _, _, _, _, _, A, _, _, _,
                             _, _, _, g, A, _, _, _, _, _, _, _, _, _, _, _, _, _, N, _}},
    {"Microhouse Minimal", 16, {A, _, _, _, _, _, _, _, N, _, _, _, _, _, _, g}},
    {"Dotted 8th Phasing", 48, {A, _, _, N, _, _, A, _, _, N, _, _, A, _, _, _,
                                _, N, _, _, A, _, _, N, _, _, A, _, _, N, _, _,
                                A, _, _, _, _, N, _, _, A, _, _, N, _, _, A, _}},
};

// Voice 1: Snare / Clap Presets
static constexpr Preset SNARE_PRESETS[16] = {
    // Row 0 (Pads 1-4)
    {"Classic Backbeat", 16, {_, _, _, _, A, _, _, _, _, _, _, _, A, _, _, _}},
    {"Backbeat & Flam", 32, {_, _, _, _, A, _, _, _, _, _, _, _, A, _, _, g,
                             _, _, _, _, A, _, _, _, _, _, _, _, A, _, g, A}},
    {"Double Clap Pump", 16, {_, _, _, _, A, _, _, _, _, _, _, _, A, N, _, _}},
    {"House Backbeat Roll", 32, {_, _, _, _, A, _, _, _, _, _, _, _, A, _, _, _,
                                 _, _, _, _, A, _, _, _, _, _, g, g, A, _, N, _}},

    // Row 1 (Pads 5-8)
    {"Dembow Syncopation", 16, {_, _, _, A, _, _, A, _, _, _, _, A, _, _, A, _}},
    {"Tresillo Snare", 32, {_, _, _, A, _, _, A, _, _, _, _, A, _, _, _, _,
                            _, _, _, A, _, _, A, _, _, _, _, A, _, A, _, _}},
    {"Afro Woodblock Drop", 16, {_, _, _, _, _, _, _, _, A, _, _, _, _, _, _, _}},
    {"Samba Caixa Roll", 32, {_, _, _, g, A, _, _, g, _, _, _, g, A, _, g, _,
                              _, _, _, g, A, _, _, g, _, g, _, g, A, N, A, _}},

    // Row 2 (Pads 9-12)
    {"UKG 2-Step Snare", 16, {_, _, _, _, A, _, _, _, _, _, _, _, A, _, N, _}},
    {"Electro 808 Snare", 32, {_, _, _, _, A, _, _, g, _, _, _, _, A, _, _, _,
                               _, _, _, _, A, _, _, g, _, _, g, _, A, _, N, _}},
    {"Breakbeat Ghost", 16, {_, _, _, _, A, _, _, g, _, g, _, _, A, _, _, g}},
    {"Baile Funk Snare", 32, {_, _, _, _, A, _, _, A, _, _, _, _, A, _, _, _,
                              _, _, _, _, A, _, _, A, _, _, _, _, A, N, A, _}},

    // Row 3 (Pads 13-16)
    {"Roll Down", 16, {A, 122, 117, 112, 106, 101, 96, 91, 86, 81, 76, 71, 65, 60, 55, g}},
    {"Roll Up", 16, {g, 55, 60, 65, 71, 76, 81, 86, 91, 96, 101, 106, 112, 117, 122, A}},
    {"Roll Up-Down", 32, {g, 55,  60,  65,  70,  75,  80, 85, 90, 95, 100, 105, 110, 115, 120, A,
                          A, 120, 115, 110, 105, 100, 95, 90, 85, 80, 75,  70,  65,  60,  55,  g}},
    {"Roll Down-Up", 32, {A, 120, 115, 110, 105, 100, 95, 90, 85, 80, 75,  70,  65,  60,  55,  g,
                          g, 55,  60,  65,  70,  75,  80, 85, 90, 95, 100, 105, 110, 115, 120, A}},
};

// Voice 2: Hi-Hat Presets
static constexpr Preset HIHAT_PRESETS[16] = {
    // Row 0 (Pads 1-4)
    {"Classic Offbeat Open", 16, {_, _, A, _, _, _, A, _, _, _, A, _, _, _, A, _}},
    {"Offbeat & Pickup", 32, {_, _, A, _, _, _, A, _, _, _, A, _, _, _, A, _,
                              _, _, A, _, _, _, A, _, _, _, A, _, _, g, A, g}},
    {"Straight 8th Notes", 16, {N, _, A, _, N, _, A, _, N, _, A, _, N, _, A, _}},
    {"Minimal Dub Ticks", 64, {_, _, A, _, _, _, _, _, _, _, A, _, _, _, _, _, _, _, _, _, _, _,
                               _, _, _, _, A, _, _, _, _, _, _, _, A, _, _, _, _, _, _, _, A, _,
                               _, _, _, g, _, _, _, _, _, _, _, _, _, _, A, _, _, _, _, _}},

    // Row 1 (Pads 5-8)
    {"UKG Swung Skip", 16, {N, _, A, _, _, g, A, _, N, _, A, _, _, g, A, _}},
    {"Breakbeat Swung 8ths", 32, {N, _, A, g, N, _, A, _, N, _, A, g, N, _, A, _,
                                  N, _, A, g, N, _, A, _, N, g, A, g, N, _, A, _}},
    {"Cumbia Guiro Scrape", 16, {_, N, _, A, _, N, _, A, _, N, _, A, _, N, _, A}},
    {"Afro Feathered Hat", 32, {_, _, A, g, _, _, A, _, _, _, A, g, _, _, A, _,
                                _, _, A, g, _, _, A, _, _, g, A, g, _, _, A, _}},

    // Row 2 (Pads 9-12)
    {"Dotted 8th Phasing", 16, {A, _, _, N, _, _, A, _, _, N, _, _, A, _, _, _}},
    {"Microhouse Delicate", 32, {_, _, A, _, _, _, _, g, _, _, A, _, _, _, _, _,
                                 _, _, A, _, _, _, _, g, _, _, A, _, _, g, _, _}},
    {"Downbeat Ticks", 16, {A, _, _, _, N, _, _, _, A, _, _, _, N, _, _, _}},
    {"Half-Time Triplet", 32, {A, _, _, N, _, _, N, _, A, _, _, N, _, _, N, _,
                               A, _, _, N, _, _, N, _, A, N, N, N, _, _, N, _}},

    // Row 3 (Pads 13-16)
    {"Chicago 909 Groove", 16, {N, g, A, g, N, g, A, g, N, g, A, g, N, g, A, g}},
    {"Detroit Electro 16ths", 32, {N, g, N, A, N, g, N, A, N, g, N, A, N, g, N, A,
                                   N, g, N, A, N, g, N, A, N, g, N, A, A, g, A, g}},
    {"Berlin Peak 16ths", 16, {A, g, N, g, A, g, N, g, A, g, N, g, A, g, N, g}},
    {"Batucada Samba Roll", 32, {A, g, A, g, A, g, A, g, A, g, A, g, A, g, A, g,
                                 A, g, A, g, A, g, A, g, A, g, A, g, A, A, A, A}},
};

// Voice 3: Percussion 1 Presets (Low/Mid)
static constexpr Preset PERC1_PRESETS[16] = {
    // Row 0 (Pads 1-4)
    {"Low Conga Tumbao", 16, {_, _, _, _, _, _, A, _, _, _, _, _, _, _, N, _}},
    {"Low Conga Bounce", 32, {_, _, _, _, _, _, A, _, _, _, _, _, _, N, _, _,
                              _, _, _, _, _, _, A, _, _, _, _, _, _, N, N, _}},
    {"Afro Low Tumbadora", 16, {A, _, _, N, _, _, A, _, _, _, N, _, _, _, _, _}},
    {"Guaguanco Low Hit", 32, {_, _, A, _, _, _, _, N, _, _, A, _, _, _, _, _,
                               _, _, A, _, _, _, _, N, _, _, A, _, _, N, _, _}},

    // Row 1 (Pads 5-8)
    {"Low Tom Downbeat", 16, {A, _, _, _, _, _, _, _, A, _, _, _, _, _, _, _}},
    {"Rolling Tribal Low", 32, {_, _, N, _, _, _, N, _, _, _, N, _, _, _, N, _,
                                _, _, N, _, _, _, N, _, _, _, N, _, _, N, A, _}},
    {"808 Low Tom Sync", 16, {_, _, _, _, _, _, A, _, _, _, _, _, _, _, A, _}},
    {"Dub Reso-Tom", 64, {_, _, _, _, A, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
                          _, _, _, _, _, _, _, _, _, _, _, _, _, _, A, _, _, _, _, _, _, _,
                          _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, A, _, _, _}},

    // Row 2 (Pads 9-12)
    {"Afro Woodblock Beat 3", 16, {_, _, _, _, _, _, _, _, A, _, _, _, _, _, _, _}},
    {"Woodblock Clack 3:2", 32, {A, _, _, N, _, _, _, A, _, _, N, _, A, _, _, _,
                                 A, _, _, N, _, _, _, A, _, _, N, _, _, _, A, _}},
    {"Sub Bass Drop 1", 16, {A, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _}},
    {"Sub Bass 2-Step", 32, {A, _, _, _, _, _, _, A, _, _, _, _, _, _, _, _,
                             A, _, _, _, _, _, _, A, _, _, _, _, _, N, _, _}},

    // Row 3 (Pads 13-16)
    {"Cumbia Low Tumbao", 16, {_, _, _, _, _, _, N, _, _, _, _, _, _, _, N, _}},
    {"Breakbeat Low Tom", 32, {_, _, _, _, _, _, _, _, N, _, _, _, _, _, _, _,
                               _, _, _, _, _, _, _, _, N, _, _, _, _, N, _, _}},
    {"Microhouse Low Wood", 16, {_, _, _, _, _, N, _, _, _, _, _, _, _, N, _, _}},
    {"Dotted 8th Low Pulse", 48, {A, _, _, N, _, _, A, _, _, N, _, _, A, _, _, _,
                                  _, N, _, _, A, _, _, N, _, _, A, _, _, N, _, _,
                                  A, _, _, _, _, N, _, _, A, _, _, N, _, _, A, _}},
};

// Voice 4: Percussion 2 Presets (Mid/High)
static constexpr Preset PERC2_PRESETS[16] = {
    // Row 0 (Pads 1-4)
    {"High Conga Slap", 16, {_, _, _, _, A, _, _, _, _, _, _, _, _, _, _, _}},
    {"Afro Conga Slaps", 32, {_, _, _, _, _, _, _, A, _, _, _, _, _, A, _, _,
                              _, _, _, _, _, _, _, A, _, _, _, _, A, _, A, _}},
    {"Rumba Clave 3:2", 32, {A, _, _, N, _, _, _, A, _, _, N, _, A, _, _, _,
                             A, _, _, N, _, _, _, A, _, _, N, _, A, _, N, _}},
    {"Son Clave 3:2", 16, {A, _, _, N, _, _, A, _, _, _, N, _, A, _, _, _}},

    // Row 1 (Pads 5-8)
    {"Syncopated Cowbell", 16, {_, _, A, _, _, _, A, _, _, _, A, _, _, _, _, _}},
    {"Campana Cumbia Bell", 32, {A, _, _, _, _, _, A, _, _, _, A, _, _, _, A, _,
                                 A, _, _, _, _, _, A, _, _, _, A, _, A, _, A, _}},
    {"808 Cowbell Sync", 16, {A, _, _, _, _, _, _, _, A, _, _, _, _, _, _, _}},
    {"Agogo Bell Mid/High", 32, {A, _, N, _, A, _, _, A, _, N, _, _, N, _, A, _,
                                 A, _, N, _, A, _, _, A, _, N, _, _, A, N, A, _}},

    // Row 2 (Pads 9-12)
    {"House Rimshot Sync", 16, {_, _, _, _, _, _, _, _, _, _, N, _, _, _, _, _}},
    {"UKG Rim Counter-Skip", 32, {_, _, _, N, _, _, _, _, _, _, _, _, _, _, _, N,
                                  _, _, _, N, _, _, _, _, _, _, N, _, _, _, _, N}},
    {"Dembow Clack Accent", 16, {_, _, _, _, _, _, _, _, _, N, _, _, _, _, _, _}},
    {"Microhouse Org Pop", 32, {_, _, _, _, _, _, A, _, _, _, _, _, _, _, _, _,
                                _, _, _, _, _, _, _, _, _, _, A, _, _, _, _, _}},

    // Row 3 (Pads 13-16)
    {"Dub Techno Stabs", 16, {_, _, A, _, _, _, _, _, _, N, _, _, _, _, _, _}},
    {"Mid Tom Response", 32, {_, _, _, _, A, _, _, _, _, _, _, _, A, _, _, _,
                              _, _, _, _, A, _, _, _, _, _, _, _, A, N, _, _}},
    {"Timbale End Roll", 32, {_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
                              _, _, _, _, _, _, _, _, _, _, _, _, A, A, N, A}},
    {"Industrial Metal Anvil", 16, {_, _, _, _, N, _, _, _, _, _, _, _, N, _, _, _}},
};

// Voice 5: Percussion 3 Presets (High/Texture)
static constexpr Preset PERC3_PRESETS[16] = {
    // Row 0 (Pads 1-4)
    {"Gentle 8th Shaker", 16, {_, g, _, N, _, g, _, N, _, g, _, N, _, g, _, N}},
    {"Minimal Shaker Touch", 32, {_, _, _, N, _, _, _, N, _, _, _, N, _, _, _, N,
                                  _, _, _, N, _, _, _, N, _, _, _, N, _, g, _, N}},
    {"Afro Seed Shaker", 16, {_, g, _, N, _, g, _, N, _, g, _, N, _, g, _, N}},
    {"Continuous 16th Shaker", 32, {g, N, g, N, g, N, g, N, g, N, g, N, g, N, g, N,
                                    g, N, g, N, g, N, g, N, g, N, g, N, g, A, g, A}},

    // Row 1 (Pads 5-8)
    {"Backbeat Tambourine", 16, {_, _, _, _, A, _, _, _, _, _, _, _, A, _, _, _}},
    {"Offbeat Tambourine", 16, {_, _, N, _, _, _, N, _, _, _, N, _, _, _, N, _}},
    {"Samba Repinique", 32, {_, g, _, N, _, g, _, N, _, g, _, N, _, g, _, N,
                             _, g, _, N, _, g, _, N, _, g, N, g, A, N, A, _}},
    {"Tamborim 16ths", 32, {A, g, N, g, A, g, N, g, A, g, N, g, A, g, N, g,
                            A, g, N, g, A, g, N, g, A, g, N, g, A, A, N, A}},

    // Row 2 (Pads 9-12)
    {"Offbeat Ride Cymbal", 16, {_, _, N, _, _, _, N, _, _, _, N, _, _, _, N, _}},
    {"Downbeat Ride Ping", 16, {A, _, _, _, _, _, _, _, A, _, _, _, _, _, _, _}},
    {"Single Ride Accent", 32, {_, _, _, _, _, _, A, _, _, _, _, _, _, _, _, _,
                                _, _, _, _, _, _, _, _, _, _, _, _, _, _, A, _}},
    {"Ride Cymbal 8ths", 16, {N, _, N, _, N, _, N, _, N, _, N, _, N, _, N, _}},

    // Row 3 (Pads 13-16)
    {"Vinyl Dust & Clicks", 64, {g, _, _, _, _, _, _, _, g, _, _, _, _, _, _, _, _, _, _, _, _, _,
                                 _, _, g, _, _, _, _, _, _, _, g, _, _, _, _, _, _, _, _, _, _, _,
                                 _, _, _, _, _, _, _, _, _, _, _, _, g, _, _, _, _, g, _, _}},
    {"Tape Crackle Echo", 16, {_, _, _, _, _, _, _, _, _, _, _, _, g, _, _, _}},
    {"High Tom Accent Roll", 32, {A, _, _, _, _, _, A, _, _, _, _, _, A, _, _, _,
                                  A, _, _, _, _, _, A, _, _, _, _, _, A, N, A, _}},
    {"Bongo Slap Flam", 32, {_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
                             _, _, _, _, _, _, _, _, _, _, _, _, _, g, N, A}},
};

inline void apply_preset(uint32_t voice, Pattern *p, uint32_t preset_index) {
  if (!p || voice >= VOICES || preset_index >= 16) {
    return;
  }
  const Preset *preset_list = nullptr;
  switch (voice) {
  case 0:
    preset_list = KICK_PRESETS;
    break;
  case 1:
    preset_list = SNARE_PRESETS;
    break;
  case 2:
    preset_list = HIHAT_PRESETS;
    break;
  case 3:
    preset_list = PERC1_PRESETS;
    break;
  case 4:
    preset_list = PERC2_PRESETS;
    break;
  case 5:
    preset_list = PERC3_PRESETS;
    break;
  default:
    return;
  }
  const Preset &preset = preset_list[preset_index];
  p->length = preset.length;
  for (uint32_t i = 0; i < PATTERN_STEPS; ++i) {
    p->steps[i] = Step(preset.velocities[i]);
  }
}

inline void apply_preset_voice(uint32_t voice, uint32_t preset_index, Pattern *p) {
  apply_preset(voice, p, preset_index);
}

// -----------------------------------------------------------------------------
// 16 Full 6-Voice Coordinated Kits
// Triggered via: FN1 + ALL + ACCENT + STEP n (for the entire kit)
//
// Voices:
//   Voice 0: Kick / Bass Drum
//   Voice 1: Snare / Clap
//   Voice 2: Hi-Hat
//   Voice 3: Percussion 1 (Low/Mid)
//   Voice 4: Percussion 2 (Mid/High)
//   Voice 5: Percussion 3 (High/Texture)
// -----------------------------------------------------------------------------

struct KitPreset {
  const char *name;
  const char *genre;
  uint8_t lengths[VOICES];
  uint8_t voices[VOICES][PATTERN_STEPS];
};

static constexpr KitPreset KITS[16] = {
    // -------------------------------------------------------------------------
    // Row 0 (Pads 1-4)
    // -------------------------------------------------------------------------
    // Kit 0 (Step 1): Classic Chicago House
    {"Classic Chicago House",
     "House",
     {16, 16, 16, 16, 16, 16},
     {
         {_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _},
         {_, _, _, _, A, _, _, _, _, _, _, _, A, _, _, _},
         {_, _, A, _, _, _, A, _, _, _, A, _, _, _, A, _},
         {_, _, _, _, _, _, A, _, _, _, _, _, _, N, _, _},
         {_, _, _, _, _, _, _, _, _, _, N, _, _, _, _, _},
         {_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _},
     }},

    // Kit 1 (Step 2): French Touch Disco
    {"French Touch Disco",
     "Nu-Disco",
     {32, 32, 16, 32, 12, 16},
     {
         {A, _, _, _, A, _, _, _, A, _, _, _, A, _, _, _,
          A, _, _, _, A, _, _, _, A, _, _, _, A, _, _, _},
         {_, _, _, _, A, _, _, _, _, _, _, _, A, _, _, _,
          _, _, _, _, A, _, _, _, _, _, _, _, A, _, _, g},
         {N, _, A, _, N, _, A, _, N, _, A, _, N, _, A, _},
         {_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, N,
          _, _, _, _, _, _, _, _, _, _, _, _, _, _, N, A},
         {_, _, A, _, _, _, A, _, _, _, A, _},
         {_, _, _, _, N, _, _, _, _, _, _, _, N, _, _, _},
     }},

    // Kit 2 (Step 3): Deep House Sunset
    {"Deep House Sunset",
     "Deep House",
     {16, 16, 16, 12, 16, 16},
     {
         {A, _, _, _, N, _, _, _, A, _, _, _, N, _, _, g},
         {_, _, _, _, A, _, _, _, _, _, _, _, A, _, _, _},
         {_, _, A, _, _, _, A, _, _, _, A, _, _, _, A, _},
         {_, _, _, _, _, _, A, _, _, _, N, _},
         {_, _, _, _, _, _, _, _, _, _, A, _, _, _, _, _},
         {_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _},
     }},

    // Kit 3 (Step 4): Garage House Shuffle
    {"Garage House Shuffle",
     "Garage House",
     {32, 32, 16, 32, 12, 16},
     {
         {A, _, _, _, N, _, _, _, A, _, _, _, N, _, _, _,
          A, _, _, _, N, _, _, _, A, _, _, _, N, _, _, g},
         {_, _, _, _, A, _, _, _, _, _, _, _, A, _, N, _,
          _, _, _, _, A, _, _, _, _, _, _, _, A, _, g, A},
         {N, _, A, _, _, g, A, _, N, _, A, _, _, g, A, _},
         {_, _, _, _, _, _, N, _, _, _, _, _, _, _, _, _,
          _, _, _, _, _, _, N, _, _, _, _, _, _, N, _, _},
         {_, _, _, N, _, _, _, _, _, _, N, _},
         {_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _},
     }},

    // -------------------------------------------------------------------------
    // Row 1 (Pads 5-8)
    // -------------------------------------------------------------------------
    // Kit 4 (Step 5): Afro-House Keinemusik
    {"Afro-House Keinemusik",
     "Afro-House",
     {16, 16, 16, 12, 12, 16},
     {
         {A, _, _, _, N, _, _, _, A, _, _, _, N, _, _, _},
         {_, _, _, _, _, _, _, _, A, _, _, _, _, _, _, _},
         {_, _, A, _, _, _, A, _, _, _, A, _, _, _, A, _},
         {A, _, _, N, _, _, A, _, _, _, N, _},
         {_, _, _, _, _, _, _, A, _, A, _, _},
         {_, g, _, N, _, g, _, N, _, g, _, N, _, g, _, N},
     }},

    // Kit 5 (Step 6): Electro-Cumbia
    {"Electro-Cumbia",
     "Cumbia",
     {32, 32, 16, 16, 12, 32},
     {
         {A, _, _, _, N, _, _, _, A, _, _, _, N, _, _, _,
          A, _, _, _, N, _, _, _, A, _, _, _, N, _, _, _},
         {_, _, _, _, A, _, _, _, _, _, _, _, A, _, _, _,
          _, _, _, _, A, _, _, _, _, _, _, _, A, _, _, g},
         {_, N, _, A, _, N, _, A, _, N, _, A, _, N, _, A},
         {_, _, _, _, _, _, N, _, _, _, _, _, _, _, N, _},
         {A, _, _, _, _, _, A, _, _, _, A, _},
         {_, _, _, _, _, _, _, _, _, _, _, _, _, _, A, _,
          _, _, _, _, _, _, _, _, _, _, _, _, _, A, N, A},
     }},

    // Kit 6 (Step 7): Dembow Latin Club
    {"Dembow Latin Club",
     "Dembow",
     {16, 16, 16, 16, 16, 16},
     {
         {A, _, _, _, A, _, _, _, A, _, _, _, A, _, _, _},
         {_, _, _, A, _, _, A, _, _, _, _, A, _, _, A, _},
         {_, _, A, _, _, _, A, _, _, _, A, _, _, _, A, _},
         {A, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _},
         {_, _, _, _, _, _, _, _, _, N, _, _, _, _, _, _},
         {_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _},
     }},

    // Kit 7 (Step 8): Batucada Carnival
    {"Batucada Carnival",
     "Samba",
     {32, 32, 16, 32, 12, 32},
     {
         {A, _, _, N, _, _, A, _, _, _, A, _, _, N, _, _,
          A, _, _, N, _, _, A, _, _, _, A, _, _, A, N, _},
         {_, _, _, g, A, _, _, g, _, _, _, g, A, _, g, _,
          _, _, _, g, A, _, _, g, _, g, _, g, A, N, A, _},
         {A, g, A, g, A, g, A, g, A, g, A, g, A, g, A, g},
         {_, _, _, _, A, _, _, _, _, _, _, _, A, _, _, _,
          _, _, _, _, A, _, _, _, _, _, _, _, A, _, N, _},
         {A, _, N, _, A, _, _, A, _, N, _, _},
         {_, g, _, N, _, g, _, N, _, g, _, N, _, g, _, N,
          _, g, _, N, _, g, _, N, _, g, N, g, A, N, A, _},
     }},

    // -------------------------------------------------------------------------
    // Row 2 (Pads 9-12)
    // -------------------------------------------------------------------------
    // Kit 8 (Step 9): UK Garage 2-Step
    {"UK Garage 2-Step",
     "UKG",
     {16, 16, 16, 16, 12, 16},
     {
         {A, _, _, _, _, _, _, A, _, _, _, _, _, _, _, _},
         {_, _, _, _, A, _, _, _, _, _, _, _, A, _, _, _},
         {N, _, A, _, _, g, A, _, N, _, A, _, _, g, A, _},
         {_, _, _, _, _, _, _, _, _, _, N, _, _, _, _, _},
         {_, _, _, N, _, _, _, _, _, _, N, _},
         {_, _, _, _, _, _, A, _, _, _, _, _, _, _, _, _},
     }},

    // Kit 9 (Step 10): Detroit Electro 808
    {"Detroit Electro 808",
     "Electro",
     {32, 32, 16, 32, 12, 16},
     {
         {A, _, _, N, _, g, _, _, A, _, _, N, _, _, N, _,
          A, _, _, N, _, g, _, _, A, _, _, N, N, _, N, _},
         {_, _, _, _, A, _, _, _, _, _, _, _, A, _, _, _,
          _, _, _, _, A, _, _, _, _, _, _, _, A, _, g, A},
         {N, g, N, A, N, g, N, A, N, g, N, A, N, g, N, A},
         {_, _, _, _, _, _, A, _, _, _, _, _, _, _, _, _,
          _, _, _, _, _, _, A, _, _, _, _, _, _, N, A, _},
         {A, _, _, _, _, _, _, _, A, _, _, _},
         {_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _},
     }},

    // Kit 10 (Step 11): Breakbeat Shuffle
    {"Breakbeat Shuffle",
     "Breaks",
     {16, 16, 16, 16, 16, 16},
     {
         {A, _, _, _, _, _, A, _, _, _, A, _, _, _, _, _},
         {_, _, _, g, A, _, _, g, _, g, _, _, A, _, _, g},
         {N, _, A, g, N, _, A, _, N, _, A, g, N, _, A, _},
         {_, _, _, _, _, _, _, _, N, _, _, _, _, _, _, _},
         {_, _, _, N, _, _, _, _, _, _, _, _, _, _, _, _},
         {_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _},
     }},

    // Kit 11 (Step 12): Baile Funk Bounce
    {"Baile Funk Bounce",
     "Bass",
     {32, 32, 16, 32, 16, 16},
     {
         {A, _, _, N, _, _, N, _, A, _, _, N, _, _, _, _,
          A, _, _, N, _, _, N, _, A, _, _, N, N, _, A, _},
         {_, _, _, _, A, _, _, _, _, _, _, _, A, _, _, _,
          _, _, _, _, A, _, _, _, _, _, _, _, A, N, A, _},
         {_, _, A, _, _, _, A, _, _, _, A, _, _, _, A, _},
         {A, _, _, _, _, _, _, _, A, _, _, _, _, _, _, _,
          A, _, _, _, _, _, _, _, A, _, _, _, _, _, _, _},
         {_, _, _, A, _, _, A, _, _, _, _, A, _, _, A, _},
         {_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _},
     }},

    // -------------------------------------------------------------------------
    // Row 3 (Pads 13-16)
    // -------------------------------------------------------------------------
    // Kit 12 (Step 13): Berlin Peak Techno
    {"Berlin Peak Techno",
     "Techno",
     {16, 16, 16, 16, 12, 16},
     {
         {A, _, _, _, A, _, _, _, A, _, _, _, A, _, _, _},
         {_, _, _, _, A, _, _, _, _, _, _, _, A, _, _, _},
         {N, g, A, g, N, g, A, g, N, g, A, g, N, g, A, g},
         {_, _, _, A, _, _, _, _, _, A, _, _, _, _, A, _},
         {_, _, _, _, N, _, _, _, _, _, _, _},
         {_, _, N, _, _, _, N, _, _, _, N, _, _, _, N, _},
     }},

    // Kit 13 (Step 14): Dub Techno Echo
    {"Dub Techno Echo",
     "Dub Techno",
     {64, 64, 64, 12, 32, 64},
     {
         {A, _, _, _, N, _, _, _, A, _, _, _, N, _, _, _, A, _, _, _, _, _,
          _, _, A, _, _, _, _, _, _, _, A, _, _, _, N, _, _, _, A, _, _, _,
          N, _, _, _, A, _, _, _, _, _, _, _, _, _, _, _, _, _, g, _},
         {_, _, _, _, _, _, _, _, A, _, _, _, _, _, _, _, _, _, _, _, _, _,
          _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, A, _, _, _,
          _, _, _, _, _, _, _, _, _, _, _, _, A, _, _, _, _, _, _, _},
         {_, _, A, _, _, _, _, _, _, _, A, _, _, _, _, _, _, _, _, _, _, _,
          _, _, _, _, A, _, _, _, _, _, _, _, A, _, _, _, _, _, _, _, A, _,
          _, _, _, _, _, _, _, _, _, _, _, _, _, _, A, _, _, _, _, g},
         {_, _, _, _, A, _, _, _, _, _, _, _},
         {_, _, A, _, _, _, _, _, _, N, _, _, _, _, _, _,
          _, _, _, _, _, _, _, _, _, _, A, _, _, N, _, _},
         {_, _, _, _, _, _, _, _, _, _, _, _, g, _, _, _, _, _, _, _, _, _,
          _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
          g, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, g, _, _, _},
     }},

    // Kit 14 (Step 15): Romanian Microhouse
    {"Romanian Microhouse",
     "Microhouse",
     {16, 16, 16, 12, 14, 32},
     {
         {A, _, _, _, N, _, _, _, A, _, _, _, N, _, _, _},
         {_, _, _, _, A, _, _, _, _, _, _, _, A, _, _, _},
         {_, _, A, _, _, _, _, g, _, _, A, _, _, _, _, _},
         {_, _, _, _, _, N, _, _, _, _, _, _},
         {_, _, _, _, _, _, A, _, _, _, _, _, _, _},
         {g, _, _, _, _, _, _, _, g, _, _, _, _, _, _, _,
          _, _, _, _, _, _, _, _, g, _, _, _, _, g, _, _},
     }},

    // Kit 15 (Step 16): Driving Hardgroove
    {"Driving Hardgroove",
     "Hardgroove",
     {32, 32, 16, 12, 32, 32},
     {
         {A, _, _, _, A, _, _, _, A, _, _, _, A, _, _, _,
          A, _, _, _, A, _, _, _, A, _, _, _, A, _, _, _},
         {_, _, _, _, A, _, _, _, _, _, _, _, A, _, _, _,
          _, _, _, _, A, _, _, _, _, _, _, _, A, _, _, g},
         {A, g, A, g, A, g, A, g, A, g, A, g, A, g, A, g},
         {_, _, N, _, _, _, N, _, _, _, N, _},
         {_, _, _, _, A, _, _, _, _, _, _, _, A, _, _, _,
          _, _, _, _, A, _, _, _, _, _, _, _, A, N, _, _},
         {A, _, _, _, _, _, A, _, _, _, _, _, A, _, _, _,
          A, _, _, _, _, _, A, _, _, _, _, _, A, N, A, _},
     }},

};

inline void apply_kit_voice(uint32_t voice, uint32_t kit_index, Pattern *p) {
  if (!p || voice >= VOICES || kit_index >= 16) {
    return;
  }
  const auto &kit = KITS[kit_index];
  uint32_t len = kit.lengths[voice];
  if (len == 0 || len > PATTERN_STEPS) {
    len = 16;
  }
  p->length = len;
  for (uint32_t i = 0; i < PATTERN_STEPS; ++i) {
    p->steps[i] = Step(kit.voices[voice][i]);
  }
}

} // namespace PatternPresets

namespace DancePatterns = PatternPresets;

#endif // PATTERN_PRESETS_H
